allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
  - '@types/react-dom@19.2.7'
  - lucide-react@1.40.0
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@tailwindcss/oxide"
